image: "python:3.7"

stages:
  - static_analysis

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: static_analysis
  before_script: []
  artifacts:
    paths: [gl-code-quality-report.json]

before_script:
  - python --version
  - pip install flake8
  - pip install mypy
  - pip install pylint
  - pip install black
  - pip install isort
  - pip install -r requirements.txt
  
flake8:
  stage: static_analysis
  script:
    - python -m flake8 --max-line-length 88 *.py

mypy:
  stage: static_analysis
  script:
    - pwd
    - ls -l
    - python -m mypy *.py

pylint:
  stage: static_analysis
  allow_failure: true
  script:
    - python -m pylint -d C0301 *.py

black:
  stage: static_analysis
  script:
    - python -m black --check *.py

isort:
  stage: static_analysis
  script:
    - python -m isort --profile black --check-only *.py
